#' Create a template for input file list
#'
#' This function generate a template for preparing the input file list, based on the
#' raw data folder structure.
#'
#' @param rawFolder a character string specifying the directory of the raw data folder
#' @return This function data frame contains the input file information
#' @export

generateInputTable <- function(rawFolder) {
    allFolder <- list.dirs(rawFolder, full.names = FALSE)
    allFolder <- allFolder[!allFolder %in% c(NA,"")]
    inputTab <- lapply(allFolder, function(eachFolder) {
        folderPath <- file.path(rawFolder, eachFolder)
        #read summary
        sumFile <- read.delim(file.path(folderPath,"summary.txt"))
        sampleName <- unique(sumFile$Experiment)
        #deal with special characters
        sampleName <- gsub("[+]", ".", sampleName)
        sampleName <- sampleName[!sampleName %in% c(NA,"")]
        #files for full proteome
        fullTab <- data.frame(fileName = rep(file.path(folderPath,"proteinGroups.txt"),length(sampleName)))
        fullTab$sample <- sampleName
        fullTab$type <- "proteome"
        phosphoTab <- data.frame(fileName = rep(file.path(folderPath,"Phospho (STY)Sites.txt"),length(sampleName)))
        phosphoTab$sample <- sampleName
        phosphoTab$type <- "phosphoproteome"
        inputTab <- rbind(fullTab, phosphoTab)
        inputTab$batch <- eachFolder
        #create a unique experimental id, in case there are duplicates for sample names, will be used as column ids
        inputTab$id <- paste0(inputTab$batch,"_",inputTab$sample)
        inputTab
    })
    inputTab <- do.call(rbind, inputTab)
}

#' Create a template for input file list (DIA)
#'
#' This function generate a template for preparing the input file list, based on the
#' raw data folder structure.
#'
#' @param rawFolder a character string specifying the directory of the raw data folder
#' @return This function data frame contains the input file information
#' @export

generateInputTable_DIA <- function(rawFolder) {
    getFile <- list.files(rawFolder, pattern = "*Labels.txt")
    #read file containing information about the experiments
    sumFile <- read.delim(file.path(rawFolder, getFile))
    #create a unique experimental id
    id <- c()
    for (i in 1: length(sumFile$Sample.Type)) {
        id <- c(id, paste(sumFile$Sample.Type[i], sumFile$treatment[i],
                          sumFile$timepoint[i], sumFile$replicate[i], sep = "_"))
    }
    #deal with special characters
    id <- gsub("[+]", ".", id)
    #file for full proteome
    getFileFP <- list.files(rawFolder, pattern = "*Protein Report.xls")
    fullTab <- data.frame(fileName = rep(file.path(rawFolder, getFileFP), length(id)))
    fullTab$type <- "proteome"
    fullTab$id <- id
    #file for phosphoproteome
    getFilePhospho <- list.files(rawFolder, pattern = "*PTM Report2.xls")
    phosphoTab <- data.frame(fileName = rep(file.path(rawFolder, getFilePhospho), length(id)))
    phosphoTab$type <- "phosphoproteome"
    phosphoTab$id <- id
    inputTab <- rbind(fullTab, phosphoTab)
}

#' Read the whole experiment
#'
#' Function to read the whole experiment and create multi-assay experiment object
#'
#' @param fileTable a data frame that contains the information of raw data files.
#' This table is normally generated by \code{generateInputTable} function.
#' @param localProbCut a numeric variable, the cut-off for localization probability for phosphoproteome data.
#' The default value is 0.75.
#' @param scoreDiffCut a numeric variable, the cut-off of score difference for phosphoproteome data.
#' The default value is 5.
#' @param fdrCut a numeric variable, the FDR cut-off for proteome data. The default value is 0.1.
#' @param scoreCut a numeric variable, the cut-off of protein scoring for proteome data. The default value is 10.
#' @param pepNumCut a numeric variable, the minial number of peptides required for quantifying a protein. The default value is 1.
#' @param ifLFQ a logic variable, whether to use LFQ normalization from MaxQuant. Default is TRUE.
#' @param annotation_col a character vector, the names of columns in the input file table that can be
#' read in as sample annotations.
#' @return This function returns a multi-assay experiment that contains the phosphoproteome and proteome data.
#' @import MultiAssayExperiment SummarizedExperiment
#' @export
#'
readExperiment <- function(fileTable, localProbCut = 0.75, scoreDiffCut = 5, fdrCut =0.1, scoreCut = 10, pepNumCut = 1, ifLFQ = TRUE, annotation_col = c()) {
    #read phospho data
    print("Processing phosphoproteomic data")
    ppe <- readPhosphoExperiment(fileTable, localProbCut, scoreDiffCut)
    #read full proteome data
    print("Processing proteomic data")
    fpe <- readProteomeExperiment(fileTable, fdrCut, scoreCut, pepNumCut, ifLFQ)
    #prepare sample annotation
    sampleTab <- fileTable[,c("id","sample","batch", annotation_col)]
    sampleTab <- sampleTab[!duplicated(sampleTab$id),]
    rownames(sampleTab) <- sampleTab$id
    sampleTab$id <- NULL
    mae <- MultiAssayExperiment(list(Phosphoproteome = ppe,
                                     Proteome = fpe),
                                sampleTab)
    return(mae)
}

#' Read the whole experiment (DIA)
#'
#' Function to read the whole experiment and create multi-assay experiment object
#'
#' @param fileTable a data frame that contains the information of raw data files.
#' This table is normally generated by \code{generateInputTable} function.
#' @param localProbCut a numeric variable, the cut-off for localization probability for phosphoproteome data.
#' The default value is 0.75.
#' @param annotation_col a character vector, the names of columns in the input file table that can be
#' read in as sample annotations.
#' @return This function returns a multi-assay experiment that contains the phosphoproteome and proteome data.
#' @import MultiAssayExperiment SummarizedExperiment
#' @export
#'
readExperimentDIA <- function(fileTable, localProbCut = 0.75, annotation_col = c()) {
    #read phospho data
    print("Processing phosphoproteomic data")
    ppe <- readPhosphoExperimentDIA(fileTable, localProbCut)
    #read full proteome data
    print("Processing proteomic data")
    fpe <- readProteomeExperimentDIA(fileTable)
    #prepare sample annotation
    sampleTab <- fileTable[,c("id", annotation_col)]
    sampleTab <- sampleTab[!duplicated(sampleTab$id),]
    rownames(sampleTab) <- sampleTab$id
    sampleTab$sample <- sampleTab$id
    sampleTab$id <- NULL
    mae <- MultiAssayExperiment(list(Phosphoproteome = ppe,
                                     Proteome = fpe),
                                sampleTab)
    return(mae)
}
